pub const DATA_TYPES: [&str; 6] = ["bytes", "uint", "int", "address", "string", "bool"];

pub const KEYWORDS: [&str; 64] = [
    "contract",
    "mapping",
    "payable",
    "using",
    "library",
    "abstract",
    "indexed",
    "call",
    "delegatecall",
    "wei",
    "gwei",
    "days",
    "weeks",
    "years",
    "emit",
    "event",
    "ether",
    "error",
    "push",
    "pop",
    "is",
    "import",
    "from",
    "assert",
    "revert",
    "while",
    "immutable",
    "mutable",
    "constant",
    "fallback",
    "calldata",
    "new",
    "cron",
    "delete",
    "receive",
    "gasless",
    "tx",
    "msg",
    "block",
    "pragma",
    "constructor",
    "enum",
    "address",
    "private",
    "struct",
    "function",
    "public",
    "views",
    "returns",
    "pure",
    "return",
    "external",
    "internal",
    "interface",
    "modifier",
    "memory",
    "if",
    "else",
    "for",
    "upgrdable",
    "constant",
    "immutable",
    "true",
    "false",
];

pub const SYMBOLS: [char; 24] = [
    '+', '-', '/', '*', '(', ')', '[', ']', '{', '}', '>', '<', '.', '=', '!', '%', ';', '\'', '"',
    ',', '|', '&', '~', '^',
];
